### ISSUE TITLE
Please do not encourage globally modifying packages

### ISSUE THREAD

**Issue by Grinnz** [srchulo/Mojo-DB-Results-Role-MoreMethods#1]
apply_roles_to_package globally modifies the package, affecting other parts of the program that might be using it and not expecting the new behavior, this is no better than monkey patching. Instead you should use create_class_with_roles or apply_roles_to_object or with_roles, this is why I created https://metacpan.org/pod/Mojo::DB::Role::ResultsRoles so roles can be applied to only the results objects created by certain instances of the database manager.

**Comment by Grinnz** [comment]
Generally speaking roles should not have import methods.

**Comment by srchulo** [comment]
So I recommend your module Mojo::DB::Role::ResultsRoles as an option in my documentation. I included the apply_roles_to_package option because in my Mojolicious apps I want every results class to have this and it was convenient for me, but I do see your point that this could have bad consequences. I'll work on removing it.

**Comment by srchulo** [comment]
@Grinnz thanks for the suggestion!
